# reacher.easy
#--auxiliary cresp \  dmc.cartpole.swingup_sparse dmc.walker.walk  --targ_extr \
#_ACTION_REPEAT = {
#    'dmc.ball_in_cup.catch': 4, 'dmc.cartpole.swingup': 8,'dmc.cartpole.swingup_sparse': 4, 'dmc.cheetah.run': 4,    
#    'dmc.finger.spin': 2, 'dmc.reacher.easy': 4, 'dmc.walker.walk': 2,'dmc.walker.stand': 4,'dmc.hopper.stand': 4
python launch.py --env dmc.walker.walk --agent drq --base sac --auxiliary cresp --num_sources 2 --dynamic -bg -tbg --disenable_default --critic_lr 5e-4 --actor_lr 5e-4 --alpha_lr 5e-4 --extr_lr 6.25e-4 --nstep_of_rsd 5 --num_sample 256 --opt_mode max --omega_opt_mode min_mu --discount_of_rs 0.8 --extr_update_via_qfloss True --cuda_id 0 -s 0 --aux_mode ras+fourier --exp_name  allft3@512-2stage1-sg-s0
python launch.py --env dmc.cartpole.balance_sparse  --cuda_id 0 -s 1 --cof_aux 0.02 --aux_mode ras+fourier --exp_name  rasf-002s-4kl-s1-3 --agent drq --base sac --auxiliary cresp --num_sources 2 --dynamic -bg -tbg --disenable_default --critic_lr 5e-4 --actor_lr 5e-4 --alpha_lr 5e-4 --extr_lr 6.25e-4 --nstep_of_rsd 5 --num_sample 256 --opt_mode max --omega_opt_mode min_mu --discount_of_rs 0.8 --extr_update_via_qfloss True 
python launch.py --env dmc.cartpole.balance_sparse  --cuda_id 0 -s 0 --aux_mode pad --exp_name  pad-s0 --agent drq --base sac --auxiliary cresp --num_sources 2 --dynamic -bg -tbg --disenable_default --critic_lr 5e-4 --actor_lr 5e-4 --alpha_lr 5e-4 --extr_lr 6.25e-4 --nstep_of_rsd 5 --num_sample 256 --opt_mode max --omega_opt_mode min_mu --discount_of_rs 0.8 --extr_update_via_qfloss True 
python launch.py --env dmc.cartpole.balance_sparse  --cuda_id 0 -s 2 --aux_mode ras+fourier --exp_name  drq-s2 --agent drq --base sac --num_sources 2 --dynamic -bg -tbg --disenable_default --critic_lr 5e-4 --actor_lr 5e-4 --alpha_lr 5e-4 --extr_lr 6.25e-4 --nstep_of_rsd 5 --num_sample 256 --opt_mode max --omega_opt_mode min_mu --discount_of_rs 0.8 --extr_update_via_qfloss True 
python launch.py --env dmc.cartpole.balance_sparse  --cuda_id 0 -s 0 --aux_mode ras+fourier --exp_name  curl-s0 --agent curl --base sac --num_sources 2 --dynamic -bg -tbg --disenable_default --critic_lr 5e-4 --actor_lr 5e-4 --alpha_lr 5e-4 --extr_lr 6.25e-4 --nstep_of_rsd 5 --num_sample 256 --opt_mode max --omega_opt_mode min_mu --discount_of_rs 0.8 --extr_update_via_qfloss True  --targ_extr 

python launch.py --env dmc.cartpole.swingup --agent drq --base sac --num_sources 2 --dynamic -bg -tbg --disenable_default --critic_lr 5e-4 --actor_lr 5e-4 --alpha_lr 5e-4 --extr_lr 5e-4 --nstep_of_rsd 5 --num_sample 256 --opt_mode max --omega_opt_mode min_mu --discount_of_rs 0.8 --extr_update_via_qfloss True --cuda_id 0 -s 10 --aux_mode ras+fourier --exp_name  Drq-s0-1